### ISSUE TITLE
i opened the site on mobile and for some godforsaken reason it printed the worble manpage in the middle of the loading screen

### ISSUE THREAD

**Issue by 18gallons** [caeserlettuce/dapug-console#39]
i have no god damned clue what happened, i can't reproduce it anymore.

**Comment by caeserlettuce** [comment]
it was probably a one time bug for something idk

**Comment by caeserlettuce** [comment]
WAIT I MAY KNOW WHAT

**Comment by caeserlettuce** [comment]
ok so you can have ?command=[command] at the end of the url, and it will automatically run that command. probably what happened was that when you loaded the console for the first time, you loaded it with a link that had ?command=worble at the end (probably) and so it displayed that

and so probably what i need to do is make it so that it will wait to run the command until after the startup

**Comment by caeserlettuce** [comment]
the aforementioned internal software controversy hath been combined with a set of supplementary solutions, and shall be annexed to the central base of modifications
